{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "cf59fc45-30b4-4f26-8d15-3535f235e813",
   "metadata": {
    "tags": []
   },
   "source": [
    "# _Trolley Tracing System_\n",
    "## ___トロリ線摩耗判定支援システム___\n",
    "\n",
    "## 👇ここからアクセス\n",
    "https://trolley-monitor-jrework.notebook.ap-northeast-1.sagemaker.aws/proxy/8501/\n",
    "\n",
    "　\n",
    "\n",
    "電車線金具モニタリングシステムからダウンロードしたパン周り画像を使用して、異常摩耗を探し出します\n",
    "\n",
    "#### ◆疑問？ コメント？\n",
    "\n",
    "疑問・コメントがありましたら、[Yammerコミュニティ](https://web.yammer.com/main/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiIxMjM0NzEzNjQwOTYifQ)へお願いします。\n",
    "\n",
    "または、下記連絡先に問い合わせてください。\n",
    "\n",
    "#### ◆問合わせ 連絡先\n",
    "テクニカルセンター(電力設備G)\n",
    "\n",
    "長山健太郎 [📫Mail][maillink]  [📢Teamsチャット][teamslink]\n",
    "\n",
    "\n",
    "[](\n",
    "メールリンク生成ページ：https://mailtolink.me/\n",
    ")\n",
    "\n",
    "[maillink]: mailto:k-nagayama@jreast.co.jp?cc=fukushima-n@jreast.co.jp&subject=%E3%80%90%E3%83%88%E3%83%AD%E3%83%AA%E7%B7%9A%E6%91%A9%E8%80%97%E5%88%A4%E5%AE%9A%E6%94%AF%E6%8F%B4%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0_%E8%B3%AA%E5%95%8F%E3%83%BB%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88%E3%80%91\n",
    "\n",
    "[teamslink]: https://teams.microsoft.com/l/chat/0/0?users=k-nagayama@jreast.co.jp,fukushima-n@jreast.co.jp&message=【トロリ線摩耗判定支援システム_質問・コメント】"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15692e85-412a-4e01-8e13-71e2cf355812",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "!pip install -r requirements.txt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fbb3edbc-6bfb-4f5b-ae6a-ed84c32a94bb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "5d943adb-d28a-4d44-b0a0-86a9e4587b7e",
   "metadata": {},
   "source": [
    "# 以下、作業用"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ab1a34c8-0397-4476-8256-c5da5dd5167d",
   "metadata": {},
   "source": [
    "## StreamlitアクセスURL\n",
    "※ノートブックインスタンスのurlに修正して使用する\n",
    "\n",
    "1. AWSノートブックインスタンス用\n",
    "\n",
    "　　https://trolley-monitor.notebook.ap-northeast-1.sagemaker.aws/proxy/8501/\n",
    "\n",
    "2. JREノートブックインスタンス用\n",
    "\n",
    "　　https://trolley-monitor-jrework.notebook.ap-northeast-1.sagemaker.aws/proxy/8501/\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "28549d70",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-05-25 09:06:58.629 INFO    numexpr.utils: NumExpr defaulting to 4 threads.\n",
      "\n",
      "Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.\n",
      "\u001b[0m\n",
      "\u001b[0m\n",
      "\u001b[34m\u001b[1m  You can now view your Streamlit app in your browser.\u001b[0m\n",
      "\u001b[0m\n",
      "\u001b[34m  Network URL: \u001b[0m\u001b[1mhttp://172.16.75.213:8501\u001b[0m\n",
      "\u001b[34m  External URL: \u001b[0m\u001b[1mhttp://54.250.87.247:8501\u001b[0m\n",
      "\u001b[0m\n",
      "\n",
      "  \u001b[34m\u001b[1mA new version of Streamlit is available.\u001b[0m\n",
      "\n",
      "  See what's new at https://discuss.streamlit.io/c/announcements\n",
      "\n",
      "  Enter the following command to upgrade:\n",
      "  \u001b[34m$\u001b[0m \u001b[1mpip install streamlit --upgrade\u001b[0m\n",
      "\u001b[0m\n",
      "2023-05-25 09:07:07.251 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 562, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 84, in <module>\n",
      "    check_graph(config)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 74, in check_graph\n",
      "    grid = vis.plot_fig_bokeh(config, base_images, rail_fpath, camera_num, img_num, graph_height)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/src/visualize.py\", line 117, in plot_fig_bokeh\n",
      "    source_upper.stream(dict(x=[], y=[], label=[f\"{math.floor((x+1)/2000)}枚目\" for x in range(len(x_values))]))\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/models/sources.py\", line 450, in stream\n",
      "    self._stream(new_data, rollover)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/models/sources.py\", line 547, in _stream\n",
      "    raise ValueError(\"All streaming column updates must be the same length\")\n",
      "ValueError: All streaming column updates must be the same length\n",
      "2023-05-25 09:09:00.682 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 562, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 84, in <module>\n",
      "    check_graph(config)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 74, in check_graph\n",
      "    grid = vis.plot_fig_bokeh(config, base_images, rail_fpath, camera_num, img_num, graph_height)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/src/visualize.py\", line 184, in plot_fig_bokeh\n",
      "    p_upper.add_tools(HoverTool(renderers=[p_upper], tooltips=tooltips))\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/model/model.py\", line 128, in __init__\n",
      "    super().__init__(**kwargs)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/has_props.py\", line 206, in __init__\n",
      "    setattr(self, name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/has_props.py\", line 230, in __setattr__\n",
      "    return super().__setattr__(name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/property/descriptors.py\", line 283, in __set__\n",
      "    value = self.property.prepare_value(obj, self.name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/property/bases.py\", line 365, in prepare_value\n",
      "    raise ValueError(f\"failed to validate {obj_repr}.{name}: {error}\")\n",
      "ValueError: failed to validate HoverTool(id='1280', ...).renderers: expected an element of either Auto or List(Instance(DataRenderer)), got [Figure(id='1138', ...)]\n",
      "2023-05-25 09:10:20.516 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 562, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 84, in <module>\n",
      "    check_graph(config)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 74, in check_graph\n",
      "    grid = vis.plot_fig_bokeh(config, base_images, rail_fpath, camera_num, img_num, graph_height)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/src/visualize.py\", line 184, in plot_fig_bokeh\n",
      "    p_upper.add_tools(HoverTool(renderers=[p_upper], tooltips=tooltips))\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/model/model.py\", line 128, in __init__\n",
      "    super().__init__(**kwargs)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/has_props.py\", line 206, in __init__\n",
      "    setattr(self, name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/has_props.py\", line 230, in __setattr__\n",
      "    return super().__setattr__(name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/property/descriptors.py\", line 283, in __set__\n",
      "    value = self.property.prepare_value(obj, self.name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/property/bases.py\", line 365, in prepare_value\n",
      "    raise ValueError(f\"failed to validate {obj_repr}.{name}: {error}\")\n",
      "ValueError: failed to validate HoverTool(id='1427', ...).renderers: expected an element of either Auto or List(Instance(DataRenderer)), got [Figure(id='1285', ...)]\n",
      "2023-05-25 09:12:04.157 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 562, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 84, in <module>\n",
      "    check_graph(config)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 74, in check_graph\n",
      "    grid = vis.plot_fig_bokeh(config, base_images, rail_fpath, camera_num, img_num, graph_height)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/src/visualize.py\", line 184, in plot_fig_bokeh\n",
      "    p_upper.add_tools(HoverTool(renderers=[p_upper], tooltips=tooltips))\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/model/model.py\", line 128, in __init__\n",
      "    super().__init__(**kwargs)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/has_props.py\", line 206, in __init__\n",
      "    setattr(self, name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/has_props.py\", line 230, in __setattr__\n",
      "    return super().__setattr__(name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/property/descriptors.py\", line 283, in __set__\n",
      "    value = self.property.prepare_value(obj, self.name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/property/bases.py\", line 365, in prepare_value\n",
      "    raise ValueError(f\"failed to validate {obj_repr}.{name}: {error}\")\n",
      "ValueError: failed to validate HoverTool(id='1567', ...).renderers: expected an element of either Auto or List(Instance(DataRenderer)), got [Figure(id='1432', ...)]\n",
      "2023-05-25 09:12:40.693 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 562, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 139, in <module>\n",
      "    check_graph(config)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 120, in check_graph\n",
      "    p_upper.add_tools(HoverTool(renderers=[p_upper], tooltips=tooltips))\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/model/model.py\", line 128, in __init__\n",
      "    super().__init__(**kwargs)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/has_props.py\", line 206, in __init__\n",
      "    setattr(self, name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/has_props.py\", line 230, in __setattr__\n",
      "    return super().__setattr__(name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/property/descriptors.py\", line 283, in __set__\n",
      "    value = self.property.prepare_value(obj, self.name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/property/bases.py\", line 365, in prepare_value\n",
      "    raise ValueError(f\"failed to validate {obj_repr}.{name}: {error}\")\n",
      "ValueError: failed to validate HoverTool(id='1707', ...).renderers: expected an element of either Auto or List(Instance(DataRenderer)), got [Figure(id='1572', ...)]\n",
      "2023-05-25 09:14:31.879 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 562, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 139, in <module>\n",
      "    check_graph(config)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 113, in check_graph\n",
      "    source_upper.stream(dict(x=[], y=[], label=[f\"{math.floor((x+1)/2000)}枚目\" for x in range(len(x_values))]))\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/models/sources.py\", line 450, in stream\n",
      "    self._stream(new_data, rollover)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/models/sources.py\", line 547, in _stream\n",
      "    raise ValueError(\"All streaming column updates must be the same length\")\n",
      "ValueError: All streaming column updates must be the same length\n",
      "2023-05-25 09:15:05.550 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 562, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 140, in <module>\n",
      "    check_graph(config)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 113, in check_graph\n",
      "    source_upper.stream(dict(x=[], y=[], label=[f\"{math.floor((x+1)/2000)}枚目\" for x in range(len(x_values))]))\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/models/sources.py\", line 450, in stream\n",
      "    self._stream(new_data, rollover)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/models/sources.py\", line 547, in _stream\n",
      "    raise ValueError(\"All streaming column updates must be the same length\")\n",
      "ValueError: All streaming column updates must be the same length\n",
      "2023-05-25 09:15:37.232 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 562, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 142, in <module>\n",
      "    check_graph(config)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 123, in check_graph\n",
      "    p_upper.add_tools(HoverTool(renderers=[p_upper], tooltips=tooltips))\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/model/model.py\", line 128, in __init__\n",
      "    super().__init__(**kwargs)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/has_props.py\", line 206, in __init__\n",
      "    setattr(self, name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/has_props.py\", line 230, in __setattr__\n",
      "    return super().__setattr__(name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/property/descriptors.py\", line 283, in __set__\n",
      "    value = self.property.prepare_value(obj, self.name, value)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/core/property/bases.py\", line 365, in prepare_value\n",
      "    raise ValueError(f\"failed to validate {obj_repr}.{name}: {error}\")\n",
      "ValueError: failed to validate HoverTool(id='2118', ...).renderers: expected an element of either Auto or List(Instance(DataRenderer)), got [Figure(id='1976', ...)]\n",
      "2023-05-25 09:16:59.696 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 562, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 140, in <module>\n",
      "    check_graph(config)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 113, in check_graph\n",
      "    source_upper.stream(dict(x=[], y=[], label=[f\"{math.floor((x+1)/2000)}枚目\" for x in range(len(x_values))]))\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/models/sources.py\", line 450, in stream\n",
      "    self._stream(new_data, rollover)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/models/sources.py\", line 547, in _stream\n",
      "    raise ValueError(\"All streaming column updates must be the same length\")\n",
      "ValueError: All streaming column updates must be the same length\n",
      "2023-05-25 09:18:40.331 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 562, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 140, in <module>\n",
      "    check_graph(config)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 113, in check_graph\n",
      "    source_upper.stream(dict(x=[], y=[], label=[f\"{math.floor((x+1)/2000)}枚目\" for x in range(len(x_values))]))\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/models/sources.py\", line 450, in stream\n",
      "    self._stream(new_data, rollover)\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/bokeh/models/sources.py\", line 547, in _stream\n",
      "    raise ValueError(\"All streaming column updates must be the same length\")\n",
      "ValueError: All streaming column updates must be the same length\n",
      "2023-05-25 10:03:09.231 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 562, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 87, in <module>\n",
      "    check_graph(config)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 72, in check_graph\n",
      "    form_graph = main_view.form()\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py\", line 231, in wrap\n",
      "    result = callable(*args, **kwargs)\n",
      "TypeError: FormMixin.form() missing 1 required positional argument: 'key'\n",
      "2023-05-25 10:08:41.192 Uncaught app exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 562, in _run_script\n",
      "    exec(code, module.__dict__)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 90, in <module>\n",
      "    check_graph(config)\n",
      "  File \"/home/ec2-user/SageMaker/AmazonSageMaker-trolley-monitor-onSOW/pages/3_📈_グラフをチェックする.py\", line 69, in check_graph\n",
      "    graph_height = form_graph.sidebar.text_input(\"グラフの表示高さを指定する(単位:px)\", \"200\")\n",
      "AttributeError: 'function' object has no attribute 'text_input'\n"
     ]
    }
   ],
   "source": [
    "!streamlit run 🖐_Hello_OHC_System.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f1d240c7-2dc0-49b7-8eb8-1b79f1ef8af5",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "!streamlit run app.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "658caaa4-fda2-445c-a395-c41281d89127",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "conda_python3",
   "language": "python",
   "name": "conda_python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
